name:                fun-with-haskell
version:             0.1.0.0
github:              "githubuser/fun-with-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/fun-with-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2.1

library:
  source-dirs: src

tests:
  fun-with-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fun-with-haskell
    - hspec
    - HUnit
    